;; Generated by :claw at 2026-01-28T00:16:20.529564Z
(asdf:defsystem #:aw-glm-bindings
  :description "Bindings generated by aw-glm"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi :claw-utils)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature (:and :x86-64 :linux))))
#-(:or (:and :x86-64 :linux))
(warn "Current platform unrecognized or unsupported by aw-glm-bindings system")